[package]
name = "ggql_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"
thiserror = "2.0.8"

[lib]
proc-macro = true
