[package]
name = "ggql"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
async-graphql = { version = "^7.0", default-features = false }
ggql_derive = { path = "../ggql-derive" }
serde = "1.0.217"
